### ISSUE TITLE
Recieving an error:  Certificate doesn't match any of the subject alternative names

### ISSUE THREAD

**Issue by colbyshores** [itzg/minecraft-server-charts#156]
When I deploy this helm chart I am receiving an error "Certificate for <launchermeta.mojang.com> doesn't match any of the subject alternative names: [*.mytrafficmanagement.com, mytrafficmanagement.com]".  I'm able to deploy the container when not using Kubernetes so I am stumped as to why this is happening.
If anyone here has encountered this issue and knows how to solve it, I would really appreciate the help.  
Thanks in advance!

`chmod: changing permissions of '/data': Operation not permitted
[init] Running as uid=1000 gid=3000 with /data as 'drwxrwsrwx 2 0 2000 4096 Jun  2 14:00 /data'
[mc-image-helper] 14:00:54.240 ERROR : 'get' command failed. Version is 1.29.1
javax.net.ssl.SSLPeerUnverifiedException: Certificate for <launchermeta.mojang.com> doesn't match any of the subject alternative names: [*.mytrafficmanagement.com, mytrafficmanagement.com]
	at org.apache.hc.client5.http.ssl.DefaultHostnameVerifier.matchDNSName(DefaultHostnameVerifier.java:165)
	at org.apache.hc.client5.http.ssl.DefaultHostnameVerifier.verify(DefaultHostnameVerifier.java:120)
	at org.apache.hc.client5.http.ssl.TlsSessionValidator.verifySession(TlsSessionValidator.java:113)
	at org.apache.hc.client5.http.ssl.SSLConnectionSocketFactory.verifySession(SSLConnectionSocketFactory.java:340)
	at org.apache.hc.client5.http.ssl.SSLConnectionSocketFactory.verifyHostname(SSLConnectionSocketFactory.java:329)
	at org.apache.hc.client5.http.ssl.SSLConnectionSocketFactory.executeHandshake(SSLConnectionSocketFactory.java:304)
	at org.apache.hc.client5.http.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:275)
	at org.apache.hc.client5.http.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:251)
	at org.apache.hc.client5.http.impl.io.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:181)
	at org.apache.hc.client5.http.impl.io.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:447)
	at org.apache.hc.client5.http.impl.classic.InternalExecRuntime.connectEndpoint(InternalExecRuntime.java:162)
	at org.apache.hc.client5.http.impl.classic.InternalExecRuntime.connectEndpoint(InternalExecRuntime.java:172)
	at org.apache.hc.client5.http.impl.classic.ConnectExec.execute(ConnectExec.java:142)
	at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
	at org.apache.hc.client5.http.impl.classic.ProtocolExec.execute(ProtocolExec.java:192)
	at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
	at org.apache.hc.client5.http.impl.classic.HttpRequestRetryExec.execute(HttpRequestRetryExec.java:96)
	at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
	at org.apache.hc.client5.http.impl.classic.ContentCompressionExec.execute(ContentCompressionExec.java:152)
	at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
	at org.apache.hc.client5.http.impl.classic.RedirectExec.execute(RedirectExec.java:115)
	at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
	at me.itzg.helpers.http.LatchingUrisInterceptor.execute(LatchingUrisInterceptor.java:27)
	at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
	at org.apache.hc.client5.http.impl.classic.InternalHttpClient.doExecute(InternalHttpClient.java:170)
	at org.apache.hc.client5.http.impl.classic.CloseableHttpClient.execute(CloseableHttpClient.java:245)
	at org.apache.hc.client5.http.impl.classic.CloseableHttpClient.execute(CloseableHttpClient.java:188)
	at org.apache.hc.client5.http.impl.classic.CloseableHttpClient.execute(CloseableHttpClient.java:162)
	at me.itzg.helpers.get.GetCommand.processSingleUri(GetCommand.java:439)
	at me.itzg.helpers.get.GetCommand.call(GetCommand.java:187)
	at me.itzg.helpers.get.GetCommand.call(GetCommand.java:54)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2041)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
	at picocli.CommandLine.execute(CommandLine.java:2170)
	at me.itzg.helpers.McImageHelper.main(McImageHelper.java:139)
`

**Comment by itzg** [comment]
> "Certificate for <launchermeta.mojang.com> doesn't match any of the subject alternative names: [*.mytrafficmanagement.com, mytrafficmanagement.com]". 

If you're not aware of that proxy, then you are experiencing a man-in-the-middle attack.

**Comment by colbyshores** [comment]
I was afraid of that.  I have everything built using IAC so I will review my code for what is pulled in to build the environment and rebuild the cluster since this is really this minecraft helm is the only pod that I am deploying outside of the base infrastructure.  It's intended to be a Hello World so to speak.

**Comment by itzg** [comment]
If that proxy is legit, then in theory it should be possible to regenerate your own CA certs with the proxy's intermediate cert and volume mount that into the container. Doesn't seem to be trivial though since a quick google search didn't seem to show what I wanted.
