### ISSUE TITLE
having issue when starting the minecraft server.

### ISSUE THREAD

**Issue by funkel1989** [itzg/minecraft-server-charts#161]
```cmd
chmod: changing permissions of '/data': Operation not permitted
[init] Running as uid=1000 gid=3000 with /data as 'drwxrwsrwx 2 0 2000 4 Jul  8 23:20 /data'
[init] Resolving type given VANILLA
[mc-image-helper] 00:36:22.176 ERROR : 'resolve-minecraft-version' command failed. Version is 1.32.6
reactor.core.Exceptions$ReactiveException: io.netty.resolver.dns.DnsResolveContext$SearchDomainUnknownHostException: Failed to resolve 'launchermeta.mojang.com' [A(1)] and search domain query for configured domains failed as well: [games.svc.cluster.local, svc.cluster.local, cluster.local, mycavanaughnetwork.com]
	at reactor.core.Exceptions.propagate(Exceptions.java:408)
	at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:100)
	at reactor.core.publisher.Mono.block(Mono.java:1712)
	at me.itzg.helpers.versions.ResolveMinecraftVersionCommand.call(ResolveMinecraftVersionCommand.java:26)
	at me.itzg.helpers.versions.ResolveMinecraftVersionCommand.call(ResolveMinecraftVersionCommand.java:12)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2041)
```

I've tried a few different things by leaving in defaults of yours and overriding some but it seems like the problem is that type is VANILLA and it can't find that version? if i'm reading the error correctly... but your default is VANILLA which is why i'm confused here. what should i be using in type to make this server start up?

```bash
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/helm.toolkit.fluxcd.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minecraft-vanilla
  namespace: games
spec:
  interval: 30m
  timeout: 15m
  chart:
    spec:
      chart: minecraft
      version: 4.9.1
      sourceRef:
        kind: HelmRepository
        name: minecraft-server
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    # deploymentAnnotations:
    #   secret.reloader.stakater.com/reload: &secret minecraft-secret
    image:
      repository: itzg/minecraft-server
      tag: latest
    resources:
      limits:
        memory: 3000Mi
      requests:
        cpu: 1000m
        memory: 2000Mi
    securityContext:
      runAsUser: 1000
      fsGroup: 1000
    livenessProbe:
      enabled: false
    readinessProbe:
      enabled: false
    startupProbe:
      enabled: false
    extraEnv:
      TZ: "${TIMEZONE}"
      ENABLE_ROLLING_LOGS: true
    persistence:
      dataDir:
        enabled: true
        existingClaim: minecraft-data-vanilla
    # serviceAnnotations:
    #   io.cilium/lb-ipam-ips: "192.168.3.10"
    minecraftServer:
      eula: true
      version: LATEST
      difficulty: normal
      whitelist: "funkel1989"
      ops: "funkel1989"
      pvp: true
      motd: "Kubernetes Hosted Minecraft Server!!! YAY!! Welcome to FunkLand"
      worldSaveName: funkland
      viewDistance: 12
      forceReDownload: true
      rcon:
        enabled: true
        serviceType: ClusterIP
        password: ${MINECRAFT_RCON_PASSWORD}
      serviceType: LoadBalancer
      extraPorts:
        - name: metrics
          containerPort: 9225
          protocol: TCP
          service:
            enabled: true
            embedded: false
            type: ClusterIP
            port: 9225
          ingress:
            enabled: false
        - name: map
          containerPort: 8123
          protocol: TCP
          service:
            enabled: true
            embedded: false
            type: ClusterIP
            port: 8123
          ingress:
            ingressClassName: nginx
            enabled: true
            annotations:
              external-dns.alpha.kubernetes.io/target: "ingress.${SECRET_DOMAIN}"
              hajimari.io/appName: Minecraft-Vanilla
              hajimari.io/enable: "true"
              hajimari.io/icon: simple-icons:minecraft
              hajimari.io/group: games
            hosts:
              - host: &host "minecraft-vanilla.${SECRET_DOMAIN}"
                paths:
                  - path: /
                    pathType: Prefix
            tls:
              - hosts:
                  - *host

```

**Comment by TheAceMan** [comment]
Might be a permissions issue, looks like your /data folder may not be accessible, looks like it would be using read/write for everyone since the user/group does not match. What type of existingClaim are you using? Is anything written to the /data directory? Try turning on debug by adding it to the extraEnv section.
```
    extraEnv:
      DEBUG: true
```
